// Package service provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.7.1 DO NOT EDIT.
package service

import (
	"time"
)

// Defines values for AppointmentAppointmentStatus.
const (
	AppointmentAppointmentStatusACTIVE AppointmentAppointmentStatus = "ACTIVE"

	AppointmentAppointmentStatusCANCELLED AppointmentAppointmentStatus = "CANCELLED"

	AppointmentAppointmentStatusCOMPLETED AppointmentAppointmentStatus = "COMPLETED"
)

// Defines values for AssociatedItemItemStatus.
const (
	AssociatedItemItemStatusACTIVE AssociatedItemItemStatus = "ACTIVE"

	AssociatedItemItemStatusCANCELLED AssociatedItemItemStatus = "CANCELLED"

	AssociatedItemItemStatusDELIVERED AssociatedItemItemStatus = "DELIVERED"

	AssociatedItemItemStatusSHIPPED AssociatedItemItemStatus = "SHIPPED"
)

// Defines values for ErrorErrorLevel.
const (
	ErrorErrorLevelERROR ErrorErrorLevel = "ERROR"

	ErrorErrorLevelWARNING ErrorErrorLevel = "WARNING"
)

// Defines values for PoaPoaType.
const (
	PoaPoaTypeCUSTOMERSIGNATURE PoaPoaType = "CUSTOMER_SIGNATURE"

	PoaPoaTypeDUMMYRECEIPT PoaPoaType = "DUMMY_RECEIPT"

	PoaPoaTypeNOSIGNATUREDUMMYPOS PoaPoaType = "NO_SIGNATURE_DUMMY_POS"

	PoaPoaTypePOARECEIPT PoaPoaType = "POA_RECEIPT"
)

// Defines values for ServiceJobServiceJobStatus.
const (
	ServiceJobServiceJobStatusCANCELLED ServiceJobServiceJobStatus = "CANCELLED"

	ServiceJobServiceJobStatusCOMPLETED ServiceJobServiceJobStatus = "COMPLETED"

	ServiceJobServiceJobStatusHOLD ServiceJobServiceJobStatus = "HOLD"

	ServiceJobServiceJobStatusNOTFULFILLABLE ServiceJobServiceJobStatus = "NOT_FULFILLABLE"

	ServiceJobServiceJobStatusNOTSERVICED ServiceJobServiceJobStatus = "NOT_SERVICED"

	ServiceJobServiceJobStatusPAYMENTDECLINED ServiceJobServiceJobStatus = "PAYMENT_DECLINED"

	ServiceJobServiceJobStatusPENDINGSCHEDULE ServiceJobServiceJobStatus = "PENDING_SCHEDULE"
)

// Defines values for ServiceLocationServiceLocationType.
const (
	ServiceLocationServiceLocationTypeINHOME ServiceLocationServiceLocationType = "IN_HOME"

	ServiceLocationServiceLocationTypeINSTORE ServiceLocationServiceLocationType = "IN_STORE"

	ServiceLocationServiceLocationTypeONLINE ServiceLocationServiceLocationType = "ONLINE"
)

// Input for add appointment operation.
type AddAppointmentRequest struct {

	// The input appointment time details.
	AppointmentTime AppointmentTimeInput `json:"appointmentTime"`
}

// The shipping address for the service job.
type Address struct {

	// The first line of the address.
	AddressLine1 string `json:"addressLine1"`

	// Additional address information, if required.
	AddressLine2 *string `json:"addressLine2,omitempty"`

	// Additional address information, if required.
	AddressLine3 *string `json:"addressLine3,omitempty"`

	// The city.
	City *string `json:"city,omitempty"`

	// The two digit country code, in ISO 3166-1 alpha-2 format.
	CountryCode *string `json:"countryCode,omitempty"`

	// The county.
	County *string `json:"county,omitempty"`

	// The district.
	District *string `json:"district,omitempty"`

	// The name of the person, business, or institution.
	Name string `json:"name"`

	// The phone number.
	Phone *string `json:"phone,omitempty"`

	// The postal code. This can contain letters, digits, spaces, and/or punctuation.
	PostalCode *string `json:"postalCode,omitempty"`

	// The state or region.
	StateOrRegion *string `json:"stateOrRegion,omitempty"`
}

// The details of an appointment.
type Appointment struct {

	// The appointment identifier.
	AppointmentId *AppointmentId `json:"appointmentId,omitempty"`

	// The status of the appointment.
	AppointmentStatus *AppointmentAppointmentStatus `json:"appointmentStatus,omitempty"`

	// The time of the appointment window.
	AppointmentTime *AppointmentTime `json:"appointmentTime,omitempty"`

	// A list of technicians assigned to the service job.
	AssignedTechnicians *[]Technician `json:"assignedTechnicians,omitempty"`

	// Proof of Appointment (POA) details.
	Poa *Poa `json:"poa,omitempty"`

	// The appointment identifier.
	RescheduledAppointmentId *AppointmentId `json:"rescheduledAppointmentId,omitempty"`
}

// The status of the appointment.
type AppointmentAppointmentStatus string

// The appointment identifier.
type AppointmentId string

// The time of the appointment window.
type AppointmentTime struct {

	// The duration of the appointment window, in minutes.
	DurationInMinutes int `json:"durationInMinutes"`

	// The date and time of the start of the appointment window, in ISO 8601 format.
	StartTime time.Time `json:"startTime"`
}

// The input appointment time details.
type AppointmentTimeInput struct {

	// The duration of an appointment in minutes.
	DurationInMinutes *int `json:"durationInMinutes,omitempty"`

	// The date, time in UTC for the start time of an appointment in ISO 8601 format.
	StartTime time.Time `json:"startTime"`
}

// Information about an item associated with the service job.
type AssociatedItem struct {

	// The Amazon Standard Identification Number (ASIN) of the item.
	Asin *string `json:"asin,omitempty"`

	// The brand name of the item.
	BrandName *string `json:"brandName,omitempty"`

	// Delivery information for the item.
	ItemDelivery *ItemDelivery `json:"itemDelivery,omitempty"`

	// The status of the item.
	ItemStatus *AssociatedItemItemStatus `json:"itemStatus,omitempty"`

	// The Amazon-defined identifier for an order placed by the buyer, in 3-7-7 format.
	OrderId *OrderId `json:"orderId,omitempty"`

	// The total number of items included in the order.
	Quantity *int `json:"quantity,omitempty"`

	// The title of the item.
	Title *string `json:"title,omitempty"`
}

// The status of the item.
type AssociatedItemItemStatus string

// Information about the buyer.
type Buyer struct {

	// The identifier of the buyer.
	BuyerId *string `json:"buyerId,omitempty"`

	// When true, the service is for an Amazon Prime buyer.
	IsPrimeMember *bool `json:"isPrimeMember,omitempty"`

	// The name of the buyer.
	Name *string `json:"name,omitempty"`

	// The phone number of the buyer.
	Phone *string `json:"phone,omitempty"`
}

// Response schema for CancelServiceJobByServiceJobId operation.
type CancelServiceJobByServiceJobIdResponse struct {

	// A list of error responses returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`
}

// Response schema for CompleteServiceJobByServiceJobId operation.
type CompleteServiceJobByServiceJobIdResponse struct {

	// A list of error responses returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`
}

// Error response returned when the request is unsuccessful.
type Error struct {

	// An error code that identifies the type of error that occurred.
	Code string `json:"code"`

	// Additional details that can help the caller understand or fix the issue.
	Details *string `json:"details,omitempty"`

	// The type of error.
	ErrorLevel *ErrorErrorLevel `json:"errorLevel,omitempty"`

	// A message that describes the error condition in a human-readable form.
	Message string `json:"message"`
}

// The type of error.
type ErrorErrorLevel string

// A list of error responses returned when a request is unsuccessful.
type ErrorList []Error

// The response schema for the GetServiceJobByServiceJobId operation.
type GetServiceJobByServiceJobIdResponse struct {

	// A list of error responses returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`

	// The job details of a service.
	Payload *ServiceJob `json:"payload,omitempty"`
}

// Response schema for GetJobs operation.
type GetServiceJobsResponse struct {

	// A list of error responses returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`

	// The payload for the GetJobs operation.
	Payload *JobListing `json:"payload,omitempty"`
}

// Delivery information for the item.
type ItemDelivery struct {

	// The date and time of the latest Estimated Delivery Date (EDD) of all the items with an EDD. In ISO 8601 format.
	EstimatedDeliveryDate *time.Time `json:"estimatedDeliveryDate,omitempty"`

	// Promised delivery information for the item.
	ItemDeliveryPromise *ItemDeliveryPromise `json:"itemDeliveryPromise,omitempty"`
}

// Promised delivery information for the item.
type ItemDeliveryPromise struct {

	// The date and time of the end of the promised delivery window, in ISO 8601 format.
	EndTime *time.Time `json:"endTime,omitempty"`

	// The date and time of the start of the promised delivery window, in ISO 8601 format.
	StartTime *time.Time `json:"startTime,omitempty"`
}

// The payload for the GetJobs operation.
type JobListing struct {

	// List of job details for the given input.
	Jobs *[]ServiceJob `json:"jobs,omitempty"`

	// A generated string used to pass information to your next request.If nextPageToken is returned, pass the value of nextPageToken to the pageToken to get next results.
	NextPageToken *string `json:"nextPageToken,omitempty"`

	// A generated string used to pass information to your next request.If previousPageToken is returned, pass the value of previousPageToken to the pageToken to get previous page results.
	PreviousPageToken *string `json:"previousPageToken,omitempty"`

	// Total result size of the query result.
	TotalResultSize *int `json:"totalResultSize,omitempty"`
}

// The Amazon-defined identifier for an order placed by the buyer, in 3-7-7 format.
type OrderId string

// Proof of Appointment (POA) details.
type Poa struct {

	// The time of the appointment window.
	AppointmentTime *AppointmentTime `json:"appointmentTime,omitempty"`

	// The type of POA uploaded.
	PoaType *PoaPoaType `json:"poaType,omitempty"`

	// A list of technicians.
	Technicians *[]Technician `json:"technicians,omitempty"`

	// The date and time when the POA was uploaded, in ISO 8601 format.
	UploadTime *time.Time `json:"uploadTime,omitempty"`

	// The identifier of the technician who uploaded the POA.
	UploadingTechnician *string `json:"uploadingTechnician,omitempty"`
}

// The type of POA uploaded.
type PoaPoaType string

// Input for rescheduled appointment operation.
type RescheduleAppointmentRequest struct {

	// The input appointment time details.
	AppointmentTime AppointmentTimeInput `json:"appointmentTime"`

	// Appointment reschedule reason code.
	RescheduleReasonCode RescheduleReasonCode `json:"rescheduleReasonCode"`
}

// Appointment reschedule reason code.
type RescheduleReasonCode string

// The scope of work for the order.
type ScopeOfWork struct {

	// The Amazon Standard Identification Number (ASIN) of the service job.
	Asin *string `json:"asin,omitempty"`

	// The number of service jobs.
	Quantity *int `json:"quantity,omitempty"`

	// A list of skills required to perform the job.
	RequiredSkills *[]string `json:"requiredSkills,omitempty"`

	// The title of the service job.
	Title *string `json:"title,omitempty"`
}

// Information about the seller of the service job.
type Seller struct {

	// The identifier of the seller of the service job.
	SellerId *string `json:"sellerId,omitempty"`
}

// The job details of a service.
type ServiceJob struct {

	// A list of appointments.
	Appointments *[]Appointment `json:"appointments,omitempty"`

	// A list of items associated with the service job.
	AssociatedItems *[]AssociatedItem `json:"associatedItems,omitempty"`

	// Information about the buyer.
	Buyer *Buyer `json:"buyer,omitempty"`

	// The date and time of the creation of the job, in ISO 8601 format.
	CreateTime *time.Time `json:"createTime,omitempty"`

	// The marketplace identifier.
	MarketplaceId *string `json:"marketplaceId,omitempty"`

	// A list of appointment windows preferred by the buyer. Included only if the buyer selected appointment windows when creating the order.
	PreferredAppointmentTimes *[]AppointmentTime `json:"preferredAppointmentTimes,omitempty"`

	// The scope of work for the order.
	ScopeOfWork *ScopeOfWork `json:"scopeOfWork,omitempty"`

	// Information about the seller of the service job.
	Seller *Seller `json:"seller,omitempty"`

	// Amazon identifier for the service job.
	ServiceJobId *ServiceJobId `json:"serviceJobId,omitempty"`

	// Information about the service job provider.
	ServiceJobProvider *ServiceJobProvider `json:"serviceJobProvider,omitempty"`

	// The status of the service job.
	ServiceJobStatus *ServiceJobServiceJobStatus `json:"serviceJobStatus,omitempty"`

	// Information about the location of the service job.
	ServiceLocation *ServiceLocation `json:"serviceLocation,omitempty"`

	// The Amazon-defined identifier for an order placed by the buyer, in 3-7-7 format.
	ServiceOrderId *OrderId `json:"serviceOrderId,omitempty"`
}

// The status of the service job.
type ServiceJobServiceJobStatus string

// Amazon identifier for the service job.
type ServiceJobId string

// Information about the service job provider.
type ServiceJobProvider struct {

	// The identifier of the service job provider.
	ServiceJobProviderId *string `json:"serviceJobProviderId,omitempty"`
}

// Information about the location of the service job.
type ServiceLocation struct {

	// The shipping address for the service job.
	Address *Address `json:"address,omitempty"`

	// The location of the service job.
	ServiceLocationType *ServiceLocationServiceLocationType `json:"serviceLocationType,omitempty"`
}

// The location of the service job.
type ServiceLocationServiceLocationType string

// Response schema for add or reschedule appointment operation.
type SetAppointmentResponse struct {

	// The appointment identifier.
	AppointmentId *AppointmentId `json:"appointmentId,omitempty"`

	// A list of error responses returned when a request is unsuccessful.
	Errors *ErrorList `json:"errors,omitempty"`

	// A list of warnings returned in the sucessful execution response of an API request.
	Warnings *WarningList `json:"warnings,omitempty"`
}

// A technician who is assigned to perform the service job in part or in full.
type Technician struct {

	// The name of the technician.
	Name *string `json:"name,omitempty"`

	// The technician identifier.
	TechnicianId *string `json:"technicianId,omitempty"`
}

// Warning returned when the request is successful but execution have some important callouts on basis of which API clients should take defined actions.
type Warning struct {

	// An warning code that identifies the type of warning that occurred.
	Code string `json:"code"`

	// Additional details that can help the caller understand or address the warning.
	Details *string `json:"details,omitempty"`

	// A message that describes the warning condition in a human-readable form.
	Message string `json:"message"`
}

// A list of warnings returned in the sucessful execution response of an API request.
type WarningList []Warning

// GetServiceJobsParams defines parameters for GetServiceJobs.
type GetServiceJobsParams struct {

	// List of service order ids for the query you want to perform.Max values supported 20.
	ServiceOrderIds *[]string `json:"serviceOrderIds,omitempty"`

	// A list of one or more job status by which to filter the list of jobs.
	ServiceJobStatus *[]GetServiceJobsParamsServiceJobStatus `json:"serviceJobStatus,omitempty"`

	// String returned in the response of your previous request.
	PageToken *string `json:"pageToken,omitempty"`

	// A non-negative integer that indicates the maximum number of jobs to return in the list, Value must be 1 - 20. Default 20.
	PageSize *int `json:"pageSize,omitempty"`

	// Sort fields on which you want to sort the output.
	SortField *GetServiceJobsParamsSortField `json:"sortField,omitempty"`

	// Sort order for the query you want to perform.
	SortOrder *GetServiceJobsParamsSortOrder `json:"sortOrder,omitempty"`

	// A date used for selecting jobs created after (or at) a specified time must be in ISO 8601 format. Required if LastUpdatedAfter is not specified.Specifying both CreatedAfter and LastUpdatedAfter returns an error.
	CreatedAfter *string `json:"createdAfter,omitempty"`

	// A date used for selecting jobs created before (or at) a specified time must be in ISO 8601 format.
	CreatedBefore *string `json:"createdBefore,omitempty"`

	// A date used for selecting jobs updated after (or at) a specified time must be in ISO 8601 format. Required if createdAfter is not specified.Specifying both CreatedAfter and LastUpdatedAfter returns an error.
	LastUpdatedAfter *string `json:"lastUpdatedAfter,omitempty"`

	// A date used for selecting jobs updated before (or at) a specified time must be in ISO 8601 format.
	LastUpdatedBefore *string `json:"lastUpdatedBefore,omitempty"`

	// A date used for filtering jobs schedule after (or at) a specified time must be in ISO 8601 format. schedule end date should not be earlier than schedule start date.
	ScheduleStartDate *string `json:"scheduleStartDate,omitempty"`

	// A date used for filtering jobs schedule before (or at) a specified time must be in ISO 8601 format. schedule end date should not be earlier than schedule start date.
	ScheduleEndDate *string `json:"scheduleEndDate,omitempty"`

	// Used to select jobs that were placed in the specified marketplaces.
	MarketplaceIds []string `json:"marketplaceIds"`
}

// GetServiceJobsParamsServiceJobStatus defines parameters for GetServiceJobs.
type GetServiceJobsParamsServiceJobStatus string

// GetServiceJobsParamsSortField defines parameters for GetServiceJobs.
type GetServiceJobsParamsSortField string

// GetServiceJobsParamsSortOrder defines parameters for GetServiceJobs.
type GetServiceJobsParamsSortOrder string

// AddAppointmentForServiceJobByServiceJobIdJSONBody defines parameters for AddAppointmentForServiceJobByServiceJobId.
type AddAppointmentForServiceJobByServiceJobIdJSONBody AddAppointmentRequest

// RescheduleAppointmentForServiceJobByServiceJobIdJSONBody defines parameters for RescheduleAppointmentForServiceJobByServiceJobId.
type RescheduleAppointmentForServiceJobByServiceJobIdJSONBody RescheduleAppointmentRequest

// CancelServiceJobByServiceJobIdParams defines parameters for CancelServiceJobByServiceJobId.
type CancelServiceJobByServiceJobIdParams struct {

	// A cancel reason code that specifies the reason for cancelling a service job.
	CancellationReasonCode string `json:"cancellationReasonCode"`
}

// AddAppointmentForServiceJobByServiceJobIdJSONRequestBody defines body for AddAppointmentForServiceJobByServiceJobId for application/json ContentType.
type AddAppointmentForServiceJobByServiceJobIdJSONRequestBody AddAppointmentForServiceJobByServiceJobIdJSONBody

// RescheduleAppointmentForServiceJobByServiceJobIdJSONRequestBody defines body for RescheduleAppointmentForServiceJobByServiceJobId for application/json ContentType.
type RescheduleAppointmentForServiceJobByServiceJobIdJSONRequestBody RescheduleAppointmentForServiceJobByServiceJobIdJSONBody
